# Generated by Django 5.2.4 on 2025-07-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, '1º Turno'), (2, '2º Turno'), (3, '3º Turno')])),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('operador', models.CharField(max_length=100)),
                ('total_produzido', models.PositiveIntegerField()),
                ('codigo_agulha', models.CharField(max_length=50)),
                ('ocorrencias', models.TextField(blank=True, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.maquina')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.turno')),
            ],
            options={
                'unique_together': {('data', 'turno', 'maquina')},
            },
        ),
    ]
