# Generated by Django 5.2.4 on 2025-07-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='numero',
            field=models.PositiveSmallIntegerField(choices=[(1, '1º Turno'), (2, '2º Turno'), (3, '3º Turno')], unique=True),
        ),
    ]
